## Author : Maharun Nasa

### First of all install numpy library .We can install it by using command promt , notebook cell or powershell terminal as our wish .
1. In command promt the syntax is : `pip install numpy`
2. In Notebook Cell the syntax is : `!pip install numpy`

### **Numpy is a powerful library for numerical computing in Python . The functions of numpy library are as follows:**
1. `Creating Arrays`: Numpy provides functions like np.array(), np.zeros(), np.ones(), and np.arange() to create arrays of different shapes and sizes.
2. `Array Manipulation`: Numpy allows you to reshape, flatten, and concatenate arrays using functions like reshape(), flatten(), and concatenate().
3. `Mathematical Operations`: Numpy supports element-wise mathematical operations such as addition, subtraction, multiplication, and division on arrays.
4. `Statistical Functions`: Numpy provides functions to compute statistical measures like mean, median, standard deviation, and variance.
5. `Linear Algebra`: Numpy includes functions for matrix operations, eigenvalues, and singular value decomposition.
6. `Random Number Generation`: Numpy has a random module that allows you to generate random numbers and perform random sampling.
7. `Broadcasting`: Numpy supports broadcasting, which allows you to perform operations on arrays of different shapes.
8. `Indexing and Slicing`: Numpy provides powerful indexing and slicing capabilities to access and manipulate array elements. You can use boolean indexing, fancy indexing, and slicing to extract specific elements or sub-arrays.
9. `File I/O`: Numpy provides functions to read and write arrays to files in various formats, such as text files and binary files.    
10. `Integration with Other Libraries`: Numpy seamlessly integrates with other scientific computing libraries like SciPy, Matplotlib, and Pandas, making it a fundamental building block for data analysis and machine learning tasks.    

In [17]:
# After installing any library we need to import it before using it.
'''Import brings in pre-written codes (modules) from a library 
so that we can use their functions in our program.'''
# Import numpy library
import numpy as np

### Numpy Array
Array is a structure for storing and retrieving data.
#### NumPy arrays have some restrictions. For instance:
- All elements of the array must be of the same type of data.
- Once created, the total size of the array can’t change.
- The shape must be “rectangular”, not “jagged”; e.g., each row of a two-dimensional array must have the same number of columns.

In [16]:
# Create a 1D numpy array
array_1d = np.array([1, 2, 3, 4, 5]) # 1D array means a single row or column of elements
print("1D Array:", array_1d)

# Create a 2D numpy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array means a matrix with rows and columns
print("2D Array:\n", array_2d)

# create a 3D numpy array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3D array means multiple matrices stacked together
print("3D Array:\n", array_3d)

# Create n-dimensional array
array_nd = np.array([1, 2, 3, 4], ndmin=5) # n-dimensional array with at least 5 dimensions it means adding extra dimensions of size 1
print("N-Dimensional Array with 5 dimensions:\n", array_nd)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
N-Dimensional Array with 5 dimensions:
 [[[[[1 2 3 4]]]]]


### You might hear of a
- A 0-D (zero-dimensional) array referred to as a `“scalar”`
- A 1-D (one-dimensional) array as a `“vector”`
- A 2-D (two-dimensional) array as a `“matrix”`
- A N-D (N-dimensional, where “N” is typically an integer greater than 2) array as a `“tensor”.`
  
For clarity, it is best to avoid the mathematical terms when referring to an array because the mathematical objects with these names behave differently than arrays (e.g. “matrix” multiplication is fundamentally different from “array” multiplication), and there are other objects in the scientific Python ecosystem that have these names (e.g. the fundamental data structure of PyTorch is the “tensor”).

### Different Method in Numpy Array 

In [15]:
array_1d = np.array([1, 2, 3, 4, 5]) # 1D array means a single row or column of elements
print("1D Array:", array_1d)

array_1d.dtype  # Get the data type of the array elements
print("Data type of 1D Array elements:", array_1d.dtype)

array_1d.max()  # Get the maximum value in the array
print("Maximum value in 1D Array:", array_1d.max())

array_1d.min()  # Get the minimum value in the array
print("Minimum value in 1D Array:", array_1d.min())

array_1d.mean()  # Get the mean (average) value of the array elements
print("Mean value of 1D Array elements:", array_1d.mean())

array_1d.sum()  # Get the sum of all elements in the array
print("Sum of all elements in 1D Array:", array_1d.sum())

# Use a numpy array so element-wise comparisons work
array2 = np.array([4, 7, 24, 31, 9, 5])
np.sort(array2)  # Sort the array in ascending order (smaller to larger numbers)
print("Sorted Array2 in ascending order:", np.sort(array2))

# Find index of the element with value 24
x = np.where(array2 == 24)
print("Index of element with value 24 in Array2:", x)

1D Array: [1 2 3 4 5]
Data type of 1D Array elements: int64
Maximum value in 1D Array: 5
Minimum value in 1D Array: 1
Mean value of 1D Array elements: 3.0
Sum of all elements in 1D Array: 15
Sorted Array2 in ascending order: [ 4  5  7  9 24 31]
Index of element with value 24 in Array2: (array([2]),)


### Slicing Array :
Slicing means getting a subset of the array

In [14]:
# Slicing syntax: array[start:end] extracts elements from index 'start' to 'end-1'
# Slicing syntax with step: array[start:end:step] extracts elements from index 'start' to 'end-1' with a step size of 'step'

array_1d = np.array([1, 2, 3, 4, 5,6,10,9])
array_1d[1:4]   # Slice the array from index 1 to 4 (excluding index 4) 
print("Sliced Array1 from index 1 to 4:", array_1d[1:4])

array_1d[:4]   # Slice the array from the start to index 4 (excluding index 4)
print("Sliced Array1 from start to index 4:", array_1d[:4])

array_1d[::2]  # Slice the array to get every second element
print("Every second element in Array1:", array_1d[::2])

array_1d[1::2]  # Slice the array to get every second element starting from index 1
print("Every second element in Array1 starting from index 1:", array_1d[1::2])

array_1d[-3:-1]  # Slice the array to get the third and second last elements
print("Third and second last elements in Array1:", array_1d[-3:-1])

Sliced Array1 from index 1 to 4: [2 3 4]
Sliced Array1 from start to index 4: [1 2 3 4]
Every second element in Array1: [ 1  3  5 10]
Every second element in Array1 starting from index 1: [2 4 6 9]
Third and second last elements in Array1: [ 6 10]


In [22]:
array_2d = np.array([[1, 2, 3,4 ,5 ,6], [7, 8, 9,10,11,12]])
print('array_2d : \n ',array_2d)
array_2d[1,1:4]  # Slice the second row from index 1 to 4 (excluding index 4)
print("Sliced second row of 2D Array from index 1 to 4:", array_2d[1,1:4])

array_2d[0:4,2]   # Slice the third column from index 0 to 4 (excluding index 4)
print("Sliced third column of 2D Array from index 0 to 4:", array_2d[0:4,2])

array_2d[0:4 , 1:3] # Slice a sub-array from rows 0 to 4 and columns 1 to 3 (excluding index 4 and 3)
print("Sliced sub-array of 2D Array from rows 0 to 4 and columns 1 to 3:\n", array_2d[0:4 , 1:3])

array_2d : 
  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
Sliced second row of 2D Array from index 1 to 4: [ 8  9 10]
Sliced third column of 2D Array from index 0 to 4: [3 9]
Sliced sub-array of 2D Array from rows 0 to 4 and columns 1 to 3:
 [[2 3]
 [8 9]]


### Genarating Dummy Variable 
Which means creating arrays filled with specific values like zeros or ones

In [23]:
np.zeros(3)  # Create a 1D array of zeros with 3 elements
print("1D Array of zeros with 3 elements:", np.zeros(3))

np.zeros((2, 4))  # Create a 2D array of zeros with 2 rows and 4 columns
print("2D Array of zeros with 2 rows and 4 columns:\n", np.zeros((2, 4)))

np.ones(5)  # Create a 1D array of ones with 5 elements
print("1D Array of ones with 5 elements:", np.ones(5))

np.ones((2, 3))  # Create a 2D array of ones with 2 rows and 3 columns
print("2D Array of ones with 2 rows and 3 columns:\n", np.ones((2, 3)))

np.linspace(0, 10, num=5) # to create an array with values that are spaced linearly in a specified interval
print("Array with values that are spaced linearly in specified interval :", np.linspace(0,10,num=5))

1D Array of zeros with 3 elements: [0. 0. 0.]
2D Array of zeros with 2 rows and 4 columns:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
1D Array of ones with 5 elements: [1. 1. 1. 1. 1.]
2D Array of ones with 2 rows and 3 columns:
 [[1. 1. 1.]
 [1. 1. 1.]]
Array with values that are spaced linearly in specified interval : [ 0.   2.5  5.   7.5 10. ]


### Arrange Array

In [24]:
np.arange(0,12,2)  # Create a 1D array with values from 0 to 12 (excluding 12) with a step of 2
print("1D Array with values from 0 to 12 with a step of 2:", np.arange(0,12,2))

arr = np.arange(-10,11) # Create a 1D array with values from -10 to 11 (excluding 11)
print("1D Array with values from -10 to 11:",arr)

np.absolute(arr)  # Get the absolute values of the elements in the array
print("Absolute values of the elements in the array:", np.absolute(arr))

1D Array with values from 0 to 12 with a step of 2: [ 0  2  4  6  8 10]
1D Array with values from -10 to 11: [-10  -9  -8  -7  -6  -5  -4  -3  -2  -1   0   1   2   3   4   5   6   7
   8   9  10]
Absolute values of the elements in the array: [10  9  8  7  6  5  4  3  2  1  0  1  2  3  4  5  6  7  8  9 10]


### Random Value

In [25]:
'''Difference between np.random.rand and np.random.randn is that 
rand generates numbers from a uniform distribution between 0 and 1, 
while randn generates numbers from a standard normal distribution (mean 0, variance 1).'''

np.random.rand(10)  # Create a 1D array of 20 random numbers between 0 and 1
print("1D Array of 20 random numbers between 0 and 1:", np.random.rand(20))

np.random.randn(20) # Create a 1D array of 20 random numbers from a standard normal distribution 
print("1D Array of 20 random numbers between 0 and 1:", np.random.rand(20))

np.random.randn(5, 3)  # Create a 2D array of random numbers with 5 rows and 3 columns
print("2D Array of random numbers with 5 rows and 3 columns:\n", np.random.randn(5, 3))

np.random.randn(4,3,2) # Create a 3D array of random numbers with 4 matrices, each having 3 rows and 2 columns
print("3D Array of random numbers with 4 matrices, each having 3 rows and 2 columns:\n", np.random.randn(4,3,2))

'''Generate a single random integer between 11 and 30 (excluding 30) .It prints a single value because no size 
is specified so the default size is 1.and the result comes as a scalar value and randomly generated each time you run it.'''
np.random.randint(11,30)
print("Single random integer between 11 and 30:", np.random.randint(11,30))

np.random.randint(11,30,4) # Generate a 1D array of 4 random integers between 11 and 30 (excluding 30)
print("1D Array of 4 random integers between 11 and 30:", np.random.randint(11,30,4))

1D Array of 20 random numbers between 0 and 1: [0.34067771 0.68463865 0.72487771 0.38974277 0.97443176 0.8615365
 0.67746772 0.71242385 0.68092423 0.91941364 0.41720143 0.04742404
 0.19690408 0.33856452 0.85047627 0.20588134 0.24189775 0.51505489
 0.79257699 0.5642665 ]
1D Array of 20 random numbers between 0 and 1: [0.24150226 0.88021484 0.69552512 0.82451893 0.66631319 0.34993799
 0.25022118 0.65249502 0.15021669 0.56896961 0.94283641 0.45400154
 0.71615965 0.02136727 0.71069439 0.98324695 0.19851215 0.92763213
 0.22471191 0.48232384]
2D Array of random numbers with 5 rows and 3 columns:
 [[-0.56623524 -0.13002783 -0.06252001]
 [ 0.47488961  0.4863711   0.17936096]
 [ 1.25339414  0.68852832  0.36894053]
 [-0.27388631  0.74802289 -0.62063116]
 [-0.43673118 -1.88318852  0.04140897]]
3D Array of random numbers with 4 matrices, each having 3 rows and 2 columns:
 [[[-1.3179176   1.33374685]
  [ 0.32655563  0.70478396]
  [-0.42830666 -1.16886908]]

 [[-0.63934741 -0.22994634]
  [-1.5405369

### Numpy Operation

In [26]:
array_1 = np.arange(2,14,3) 
print("1D Array with values from 2 to 14 with a step of 3:", array_1)

array_1+array_1  # Element-wise addition of two arrays
print("Element-wise addition of array_1 with itself:", array_1+array_1)

array_1-array_1  # Element-wise subtraction of two arrays
print("Element-wise subtraction of array_1 from itself:", array_1-array_1)

array_1*array_1  # Element-wise multiplication of two arrays
print("Element-wise multiplication of array_1 with itself:", array_1*array_1)

array_1/array_1  # Element-wise division of two arrays
print("Element-wise division of array_1 by itself:", array_1/array_1)

array_1**2  # Element-wise exponentiation of the array (square each element)
print("Element-wise exponentiation of array_1 (square each element):", array_1**2)

array_1**array_1  # Element-wise exponentiation of the array (raise each element to the power of itself)
print("Element-wise exponentiation of array_1 (raise each element to the power of itself):", array_1**array_1)

array_1+10  # Element-wise addition of 10 to each element in the array
print("Element-wise addition of 10 to each element in array_1:", array_1+10)

np.sqrt(array_1)  # Element-wise square root of the array
print("Element-wise square root of array_1:", np.sqrt(array_1))

np.max(array_1)  # Get the maximum value in the array
print("Maximum value in array_1:", np.max(array_1))

np.sin(array_1)  # Element-wise sine of the array (angle in radians)
print("Element-wise sine of array_1 (angle in radians):", np.sin(array_1))

1D Array with values from 2 to 14 with a step of 3: [ 2  5  8 11]
Element-wise addition of array_1 with itself: [ 4 10 16 22]
Element-wise subtraction of array_1 from itself: [0 0 0 0]
Element-wise multiplication of array_1 with itself: [  4  25  64 121]
Element-wise division of array_1 by itself: [1. 1. 1. 1.]
Element-wise exponentiation of array_1 (square each element): [  4  25  64 121]
Element-wise exponentiation of array_1 (raise each element to the power of itself): [           4         3125     16777216 285311670611]
Element-wise addition of 10 to each element in array_1: [12 15 18 21]
Element-wise square root of array_1: [1.41421356 2.23606798 2.82842712 3.31662479]
Maximum value in array_1: 11
Element-wise sine of array_1 (angle in radians): [ 0.90929743 -0.95892427  0.98935825 -0.99999021]


### Reshape of an Array

In [27]:
array_1d = np.arange(1,13) # Create a 1D array with values from 1 to 12
print("1D Array with values from 1 to 12:", array_1d)

# Now making this 1d array to a 2d array by reshaping it .
new_array_2d = array_1d.reshape(3,4)  # Reshape the 1D array into a 2D array with 3 rows and 4 columns
print("Reshaped 2D Array (3 rows, 4 columns):\n", new_array_2d) 

# Now making this 1d array to a 3d array by reshaping it .
new_array_3d = array_1d.reshape(2,3,2)  # Reshape the 1D array into a 3D array with 2 matrices, each having 3 rows and 2 columns
print("Reshaped 3D Array (2 matrices, each with 3 rows and 2 columns):\n", new_array_3d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print('2d array :',array_2d)

# Now flattening this 2d array to 1d array
flattened_array = array_2d.flatten()  # Flatten the 2D array into a 1D array
print("Flattened 1D Array:", flattened_array)

# Or
arr_1d = array_2d.reshape(-1)  # Reshape the 2D array into a 1D array using -1 to automatically calculate the size
print("Reshaped 1D Array using -1:", arr_1d)

1D Array with values from 1 to 12: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped 2D Array (3 rows, 4 columns):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Reshaped 3D Array (2 matrices, each with 3 rows and 2 columns):
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
2d array : [[1 2 3]
 [4 5 6]]
Flattened 1D Array: [1 2 3 4 5 6]
Reshaped 1D Array using -1: [1 2 3 4 5 6]


### Joining Numpy Array 

In [28]:
arr1 = np.array([1,3,4,5])
arr2 = np.array([2,3,5,6])

# Concatenate two arrays into one, which means joining two arrays by appending the elements of the second array to the first array
np.concatenate((arr1, arr2)) 
print("Concatenated Array of arr1 and arr2:", np.concatenate((arr1, arr2)))

arr3 = np.array([[4,5,6],[7,8,9]])
arr4 = np.array([[22,34,23],[33,37,39]])
np.concatenate((arr3, arr4)) # Concatenate two 2D arrays along rows (vertical stacking) ,which means appending the rows of the second array to the first array
print("Concatenated 2D Array of arr3 and arr4 along rows:\n", np.concatenate((arr3, arr4)))

np.concatenate((arr3,arr4),axis=0) # Concatenate two 2D arrays along rows (vertical stacking)
print("Concatenated 2D Array of arr3 and arr4 along rows using axis=0:\n", np.concatenate((arr3,arr4),axis=0))

np.concatenate((arr3,arr4),axis=1) # Concatenate two 2D arrays along columns (horizontal stacking) ,which means appending the columns of the second array to the first array
print("Concatenated 2D Array of arr3 and arr4 along columns using axis=1:\n", np.concatenate((arr3,arr4),axis=1))

# The axis along which the arrays will be joined. If axis is None, arrays are flattened before use. Default is 0.
# axis = 0 indicates row & axis = 1 indicates column 

Concatenated Array of arr1 and arr2: [1 3 4 5 2 3 5 6]
Concatenated 2D Array of arr3 and arr4 along rows:
 [[ 4  5  6]
 [ 7  8  9]
 [22 34 23]
 [33 37 39]]
Concatenated 2D Array of arr3 and arr4 along rows using axis=0:
 [[ 4  5  6]
 [ 7  8  9]
 [22 34 23]
 [33 37 39]]
Concatenated 2D Array of arr3 and arr4 along columns using axis=1:
 [[ 4  5  6 22 34 23]
 [ 7  8  9 33 37 39]]


### Spliting Numpy Array

In [30]:
arr = np.arange(1,10) 
print("1D Array with values from 1 to 10:", arr)

# Now spliting the array into 3 parts 
splited_arrays = np.array_split(arr, 3)  # Split the array into 3 equal parts
print("Splited Arrays into 3 parts:", splited_arrays)

# Get Accessing individual splited arrays
print("First splited array:", splited_arrays[0])
print("Second splited array:", splited_arrays[1])
print("Third splited array:", splited_arrays[2])

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
print("2D Array arr2:\n", arr2)
# Now spliting the 2d array into 3 parts along rows
splited_2d_arrays = np.array_split(arr2, 3)  # Split the 2D array into 3 parts along rows
print("Splited 2D Arrays into 3 parts along rows:", splited_2d_arrays)

# Get Accessing individual splited 2d arrays
print("First splited 2D array:\n", splited_2d_arrays[0])
print("Second splited 2D array:\n", splited_2d_arrays[1])
print("Third splited 2D array:\n", splited_2d_arrays[2])

1D Array with values from 1 to 10: [1 2 3 4 5 6 7 8 9]
Splited Arrays into 3 parts: [array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
First splited array: [1 2 3]
Second splited array: [4 5 6]
Third splited array: [7 8 9]
2D Array arr2:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
Splited 2D Arrays into 3 parts along rows: [array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]
First splited 2D array:
 [[1 2 3]
 [4 5 6]]
Second splited 2D array:
 [[ 7  8  9]
 [10 11 12]]
Third splited 2D array:
 [[13 14 15]
 [16 17 18]]


### You can stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, `a1` and `a2`:

In [34]:
a1 = np.array([[1, 1],
               [2, 2]])
print("a1",a1)

a2 = np.array([[3, 3],
               [4, 4]])
print('a2:',a2)

a1 [[1 1]
 [2 2]]
a2: [[3 3]
 [4 4]]


In [33]:
# You can stack them vertically with vstack:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [32]:
# stack them horizontally with hstack:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

### Generating random numbers
```
The use of random number generation is an important part of the configuration and evaluation of many numerical and machine learning algorithms. Whether you need to randomly initialize weights in an artificial neural network, split data into random sets, or randomly shuffle your dataset, being able to generate random numbers (actually, repeatable pseudo-random numbers) is essential.
```
With Generator.integers, you can generate random integers from low (remember that this is inclusive with NumPy) to high (exclusive). You can set endpoint=True to make the high number inclusive.

You can generate a 2 x 4 array of random integers between 0 and 4 with:

In [31]:
# Create a Generator instance before using it
rng = np.random.default_rng()
rng.integers(5, size=(2, 4))

array([[4, 1, 1, 0],
       [2, 4, 1, 1]])